Repository joaobarbirato/EscolaApp-Web, pull requests merged in 2018-12, with the labels that each got.

#4 Criados formulários de Login
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/forms.py
  accounts/models.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  escolaappweb/settings.py
  escolaappweb/urls.py
  escolaappweb_dashboard/templates/dashboard/index.html
  escolaappweb_dashboard/urls.py
  escolaappweb_dashboard/views.py
Labels: enhancement

#11 Adicionado get_random_string em SECRET_KEY
  escolaappweb/settings.py
Labels: bug, invalid

#13 Esboçando os models.
  escolaappweb_dashboard/models.py
Labels: enhancement

#15 [WIP] Adicionados forms de modelos
  escolaappweb_dashboard/constants.py
  escolaappweb_dashboard/form_views.py
  escolaappweb_dashboard/forms.py
  escolaappweb_dashboard/models.py
  escolaappweb_dashboard/templates/dashboard/create.html
  escolaappweb_dashboard/templates/dashboard/index.html
  escolaappweb_dashboard/urls.py
  escolaappweb_dashboard/views.py
Labels: enhancement

#27 Corrigidos HREFs em create.html
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  escolaappweb_dashboard/templates/dashboard/create.html
Labels: invalid
